services:
    postgres:
        image: "postgres:alpine3.20"
        environment:
            - "POSTGRES_DB=reminder"
            - "POSTGRES_PASSWORD=password"
            - "POSTGRES_USER=thomas"
        ports:
            - "5433:5432"
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - "8080:8080"
